repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.1-1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: autopep8-wrapper
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: flake8
      - id: requirements-txt-fixer
      - id: detect-private-key
  - repo: https://github.com/asottile/reorder_python_imports
    sha: v1.1.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/mirrors-autopep8
    sha: v1.4.2
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/add-trailing-comma
    sha: v0.7.1
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/asottile/yesqa
    rev: v0.0.8
    hooks:
      - id: yesqa
